#based image dari ubuntuh ttps://hub.docker.com/_/ubuntu
FROM ubuntu:20.04

LABEL maintainer="udarizki2020@gmail.com"

#run --> perintah ketika membuat image
RUN apt-get update

#cmd --> perintah ketika di jalankan sebagai container
CMD [ "echo", "Hello ini dari container local" ]
