#ambil based image dari ubuntu
FROM ubuntu:20.04  
LABEL maintainer="udarizki2020@gmail.com"
#akan menjalankan perintah setelah perintah run
#contoh RUN MKDIR coba : Perintah untuk membuat folder coba

RUN apt-get update
#beda run dengan cmd
#run : menjalankan image
#cmd : ketika container dijalankan
CMD ["echo", "Halo dari container  ..."]